services:
  - type: web
    name: face-code-backend
    runtime: docker
    dockerContext: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
